name: MacOS Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.7]
        rasa-version: [2.5]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade rasa[spacy]==${{ matrix.rasa-version }}
        python -m pip install pytest pyvi
    - name: Test with pytest
      run: |
        python -m pip install -e ".[all]"
        python -m pip freeze
        python tests/scripts/prepare_fasttext.py
        chmod 775 tests/data/fasttext/custom_fasttext_model.bin
        pytest
