name: Python Non Ubuntu Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.7]
        rasa-version: ["1.10.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade rasa==${{ matrix.rasa-version }}
        python -m pip install pytest
    - name: Test with pytest
      run: |
        python -m pip install -e "."
        python -m pip freeze
        python tests/prepare_everything.py
        chmod 775 tests/data/custom_fasttext_model.bin
        pytest
